dockerfile: |-
  RUN apk add --no-cache build-base git yaml-dev
  RUN gem install gem_hadar

script: &script |-
  echo -e "\e[1m"
  ruby -v
  rm -f Gemfile.lock
  bundle install --jobs=$(getconf _NPROCESSORS_ONLN)
  echo -e "\e[0m"
  rake test

images:
  ruby:3.4-alpine: *script
  ruby:3.3-alpine: *script
  ruby:3.2-alpine: *script
