services:
  redis:
    image: valkey/valkey:7.2.7-alpine
    restart: unless-stopped
    ports: [ "127.0.0.1:9736:6379" ]
    volumes:
      - "redis-data:/data:delegated"
      - "./config/redis.conf:/etc/redis.conf"
volumes:
  redis-data:
